# Generated by Django 4.2.4 on 2023-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.CharField(default='', max_length=100)),
                ('cover', models.ImageField(blank=True, default='', upload_to='categories/covers/%Y/%m/%d/')),
            ],
        ),
    ]
