# Generated by Django 4.2.4 on 2023-08-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interested_user',
        ),
    ]
