# Generated by Django 4.2.4 on 2023-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Title')),
                ('description', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('invited_players', models.IntegerField(default=1)),
                ('cover', models.ImageField(blank=True, default='', upload_to='posts/covers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
