# Generated by Django 4.2.4 on 2023-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_remove_interest_interested_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, default='', to='interests.interest'),
        ),
    ]
