# Generated by Django 4.2.4 on 2023-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord_profile_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
