# Generated by Django 4.2.4 on 2023-08-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='categories/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=65),
        ),
    ]
